---
- hosts: all
  become: yes
  tasks:
   - name: install Containerd
     apt:
       name: containerd
       state: present
       update_cache: true
   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present
   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'
   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true
   - name: install kubeadm
     apt:
       name: kubeadm
       state: present
   - name: install kubectl
     apt:
       name: kubectl
       state: present
       force: yes
   - name: Setup Modules
     copy:
      dest: "/etc/modules-load.d/k8s.conf"
      content: |
        br_netfilter
        
   - name: Load br_netfilter
     command: modprobe br_netfilter
   - name: Setup Sysctls
     copy:
      dest: "/etc/sysctl.d/k8s.conf"
      content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
   - name: Reapply sysctls
     command: sysctl --system

   - name: remove swap
     shell: swapoff -a

   - name: disable swap in fstab
     shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
